import './globals.css'

export const metadata = {
  title: 'create-a-simple-app-to-test-deploy-to-vercel-20251019-045101',
  description: 'Generated by Neuronix',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}